language: java
sudo: required

jdk:
  - oraclejdk8

addons:
  ssh_known_hosts:
    - kneecapdev.com
  apt:
    packages:
      - sshpass

before_install:
  - sudo apt-get update -qq
  - sudo usermod -a -G audio travis
  - sudo apt-get install -y portaudio19-dev
  - sudo apt-get install libasound2-dev alsa-utils alsa-oss
  - sudo bash init_dummy_sound.sh
  - sudo modprobe snd-dummy
  - pip install --user codecov

script:
  - gradle assemble
  - sudo gradle check --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - codecov
  - gradle assemble -Pportable=true
  - chmod +x deploy.sh
  - ./deploy.sh