language: java
sudo: required

jdk:
  - oraclejdk8

addons:
  ssh_known_hosts:
    - kneecapdev.com

before_install:
  - pip install --user codecov
  - sudo apt-get update -qq
  - sudo apt-get install -qq sshpass

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - codecov
  - gradle assemble -Pportable=true
  - chmod +x deploy.sh
  - ./deploy.sh